### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [google/go-querystring#11]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-querystring and versioning would help Debian keep up with development.

**Comment by jredville** [comment]
This would also help with projects using Glide or other version based dependency management

**Comment by willnorris** [comment]
closing as "will not implement".  See google/go-github#376 for discussion.

**Comment by aviau** [comment]
It looks like semver will be used after all?

From: https://github.com/google/go-github/issues/376

> I haven't heard adamant opposition to moving forward with semver tagging, so I'm going to plan on that being the path forward. 

Should we reopen?

**Comment by shurcooL** [comment]
> Should we reopen?

We've already reopened issue #376 and tracking it there.

**Comment by gmlewis** [comment]
Reopening and assigning to Will.

**Comment by willnorris** [comment]
done.
