### ISSUE TITLE
Support for Unmarshaler / Marshaler

### ISSUE THREAD

**Issue by tamccall** [google/go-querystring#34]
The golang json package exposes interfaces that allows types to define how they will be marshalled into/(out of) json.

- https://golang.org/src/encoding/json/decode.go?s=4749:4808#L107
- https://golang.org/src/encoding/json/encode.go?s=8424:8483#L216

Would like to see similar interfaces in this package.

**Comment by hetiansu5** [comment]
> The golang json package exposes interfaces that allows types to define how they will be marshalled into/(out of) json.
> 
> * https://golang.org/src/encoding/json/decode.go?s=4749:4808#L107
> * https://golang.org/src/encoding/json/encode.go?s=8424:8483#L216
> 
> Would like to see similar interfaces in this package.

an URL Query string Encoder and Parser. It works well.

https://github.com/hetiansu5/urlquery

**Comment by willnorris** [comment]
values can implement the [query.Encoder](https://pkg.go.dev/github.com/google/go-querystring/query#Encoder) interface, which allows customizing how values are encoded.  go-querystring doesn't currently support parsing query strings.
