### ISSUE TITLE
"query string" for GitHub search

### ISSUE THREAD

**Issue by oprogramador** [google/go-querystring#38]
When I search `querystring` https://github.com/search?l=Go&o=desc&q=querystring&s=stars&type=Repositories, this package is the most starred but when I search `query string` https://github.com/search?l=Go&o=desc&q=query+string&s=stars&type=Repositories, this package isn't on the list.

Therefore I guess, adding the `query string` keyword to the GitHub description, topics and README would simplify finding the package.

**Comment by willnorris** [comment]
updated repo description.  Apparently topics can't have spaces, so I added `query-string`.  Thanks for tip.
