### ISSUE TITLE
can you please update the tag? 

### ISSUE THREAD

**Issue by edyesed** [google/go-querystring#47]
Hi,
There are some recent updates in this package that I'd like to import via dependency, but when I get the latest release, it is several years old. 
Thanks,

**Comment by tanmng** [comment]
@edyesed If you need this in a pinch, maybe you can try using a go get command such as follow to update your `go.mod` and `go.sum` to use latest commit from the repo:

```sh
go get github.com/google/go-querystring/query@e9ef1ee
```

note the commit `e9ef1ee` is the last one from `master` branch. I tried running test against the commit and everything passed so I think it is safe to use it.

**Comment by willnorris** [comment]
Yeah, will do.  I had done a decent amount of work on it in the last few weeks, and was originally waiting to finish one more thing... maybe it was adding more samples to the README file?  In any event, I'll go ahead and get this tagged now and add more docs later.

**Comment by willnorris** [comment]
done... latest commit now also tagged as "v1.1.0".
