### ISSUE TITLE
Supporting slices

### ISSUE THREAD

**Issue by Integralist** [google/go-querystring#60]
👋🏻 

I'm trying to encode:

```go
type Example struct 
	Services  []string   `url:"services,omitempty"`
}
```

But I'm seeing the encoded values equate to `services=A&services=B` as apposed to what I was hoping to get back, which was `services[]=A&services[]=B`.

Is there a way to achieve this using this library?

I'm taking over a project which has a similar bug but the project uses https://github.com/ajg/form where it encodes as `services.0=A&services.1=B`.

Thanks.

**Comment by willnorris** [comment]
https://pkg.go.dev/github.com/google/go-querystring/query#Values documents all of the different options available.  In your case, you want to add the "brackets" option:

``` go
type Example struct 
	Services  []string   `url:"services,brackets,omitempty"`
}
```

**Comment by Integralist** [comment]
Oh that's awesome. Thank you!

Apologies for wasting your time (due to me clearly not searching the docs hard enough). My bad.
