### ISSUE TITLE
Support pointer method (*Type)EncodeValues on the Encoder interface

### ISSUE THREAD

**Issue by isaacwein** [google/go-querystring#85]
On the Encoder interface if the method will be defined as a pointer on the type it will be ignored even if it got implemented 

````go
type Working bool

func (d Working) EncodeValues(k string, v *url.Values) error {
	if d {
		v.Add(k, "yes")
	} else {
		v.Add(k, "no")
	}
	return nil
}

type NotWorking bool
// as a pointer EncodeValues
func (d *NotWorking) EncodeValues(k string, v *url.Values) error {
	if d != nil && *d {
		v.Add(k, "yes")
	} else {
		v.Add(k, "no")
	}
	return nil
}
````

[go playground](https://goplay.tools/snippet/urdB5ppq2aJ)

**Comment by willnorris** [comment]
For the go playground example you gave, this is working as intended, as this is how go interfaces work.  If the method is defined with a pointer receiver, then the non-pointer type does not implement the interface.  Here's a pretty succinct explanation: https://sentry.io/answers/interface-pointer-receiver/

For this to work, your B field would need to be a pointer to NotWorking...

```go
type MyQueries struct {
	A Working    `url:"a"`
	B *NotWorking `url:"b"`
}

func main() {
        b := NotWorking(true)
	data := &MyQueries{
		A: true,
		B: &NotWorking(true),
	}
}
```

**Comment by isaacwein** [comment]
thank you for clerifying
